### ISSUE TITLE
Feature: 모의투자 

### ISSUE THREAD

**Issue by milowon** [QuantWebProject/QuantWeb-SpringServer-#19]
## 어떤 기능인가요?

모의투자 전략을 저장,수정,삭제,조회 

## Todo

- [ ] 모의투자 전략 저장
- [ ] 모의투자 전략 수정
- [ ] 모의투자 전략 삭제
- [ ] 모의투자 전략 조회
